// license_test.go
package molotov

import (
   "encoding/json"
   "os"
   "testing"
)

func TestGetLicense(t *testing.T) {
   // Read the asset data generated by TestGetAsset
   assetFile, err := os.ReadFile("asset_test.json")
   if err != nil {
      t.Fatalf("Failed to read asset_test.json. Please run TestGetAsset first: %v", err)
   }

   // TestAssetData is defined in asset_test.go
   var assetData TestAssetData
   if err := json.Unmarshal(assetFile, &assetData); err != nil {
      t.Fatalf("Failed to unmarshal asset data: %v", err)
   }

   if assetData.LicenseURL == "" {
      t.Fatal("License URL is empty in asset_test.json")
   }

   t.Logf("Requesting license from: %s", assetData.LicenseURL)

   // Call GetLicense with a nil challenge as requested
   license, err := GetLicense(assetData.LicenseURL, assetData.DtAuthToken, nil)
   if err != nil {
      // This is expected to fail (e.g., HTTP 400 Bad Request) because the Widevine payload is nil.
      t.Fatalf("GetLicense failed (this is expected with a nil challenge!): %v", err)
   }

   if len(license) == 0 {
      t.Fatal("Expected license data, got empty response")
   }

   t.Logf("Successfully retrieved license data, length: %d bytes", len(license))
}
