// user_test.go
package molotov

import (
   "encoding/json"
   "os"
   "testing"
)

func TestGetUser(t *testing.T) {
   // Read the auth data generated by TestSignin
   authFile, err := os.ReadFile("auth_test.json")
   if err != nil {
      t.Fatalf("Failed to read auth_test.json. Please run TestSignin first: %v", err)
   }

   // TestAuthData is defined in signin_test.go
   var authData TestAuthData
   if err := json.Unmarshal(authFile, &authData); err != nil {
      t.Fatalf("Failed to unmarshal auth data: %v", err)
   }

   if authData.AccessToken == "" {
      t.Fatal("Access token is empty in auth_test.json")
   }

   userID, profileID, err := GetUser(authData.AccessToken)
   if err != nil {
      t.Fatalf("GetUser failed: %v", err)
   }

   if userID == "" || profileID == "" {
      t.Fatalf("Expected non-empty userID and profileID, got userID=%q, profileID=%q", userID, profileID)
   }

   // Prepare the data to be written for future tests (e.g., GetAsset)
   userData := TestUserData{
      UserID:    userID,
      ProfileID: profileID,
   }

   data, err := json.MarshalIndent(userData, "", "  ")
   if err != nil {
      t.Fatalf("Failed to marshal user data: %v", err)
   }

   // Write the resulting user ID and profile ID to a file
   err = os.WriteFile("user_test.json", data, 0600)
   if err != nil {
      t.Fatalf("Failed to write user data to file: %v", err)
   }

   t.Logf("Successfully retrieved User ID (%s) and Profile ID (%s) and saved to user_test.json", userID, profileID)
}

// TestUserData is used to serialize the user and profile IDs for future tests.
type TestUserData struct {
   UserID    string `json:"user_id"`
   ProfileID string `json:"profile_id"`
}
